### PR TITLE
Fix build and Update Freedesktop SDK 21.08

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
seem to work fine.

**Comment by marin-m** [comment]
Hello,

Do you have an idea of what the "removal of the Rust SDK" mentioned here: https://www.phoronix.com/scan.php?page=news_item&px=Freedesktop-SDK-21.08 really means?

Thank you,

**Comment by hfiguiere** [comment]
> Hello,
> 
> Do you have an idea of what the "removal of the Rust SDK" mentioned here: https://www.phoronix.com/scan.php?page=news_item&px=Freedesktop-SDK-21.08 really means?
> 
> Thank you,

You should ask the author what he meant, because to me it sounds like it is incorrect.

**Comment by hfiguiere** [comment]
but this is irrelevant to this PR it
1. fix a syntax error that broke the build
2. use the latest runtime.

**Comment by marin-m** [comment]
Thank you!

**Pull request merged**
